# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-22 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlShorter',
            fields=[
                ('key', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=250, unique=True)),
                ('last_enter_url', models.URLField(max_length=250)),
            ],
        ),
    ]
